Q1 a)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]

print(reversed_arr)  # Output: [5 4 3 2 1]


[5 4 3 2 1]


In [ ]:
Q1 b)

In [20]:
import numpy as np

arr1=np.array([1,2,3],[2,4,5],[1,2,3])

# Method 1: Using flatten()
flat1 = arr1.flatten()

# Method 2: Using ravel() Flatten means array of 1d bana dena 
flat2 = arr1.ravel()


print("Using flatten():", flat1)
print("Using ravel():", flat2)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
import numpy as np

arr=np.array([1,2,3],[2,4,5],[1,2,3])

# Method 1: Using flatten()
flat1 = arr.flatten()

# Method 2: Using ravel() Flatten means array of 1d bana dena 
flat2 = arr.ravel()


print("Using flatten():", flat1)
print("Using ravel():", flat2)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# Method 1: Using flatten()
flat1 = arr.flatten()

# Method 2: Using ravel() Flatten means array of 1d bana dena 
flat2 = arr.ravel()


print("Using flatten():", flat1)
print("Using ravel():", flat2)

Using flatten(): [1 2 3 2 4 5 1 2 3]
Using ravel(): [1 2 3 2 4 5 1 2 3]


Q1 c)

In [ ]:
import numpy as np

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])


result = np.array_equal(arr1, arr2)
print("Arrays are equal:", result)



Arrays are equal: True


In [ ]:
import numpy as np

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[5,4]])


result = np.array_equal(arr1, arr2)
print("Arrays are equal:", result)

Arrays are equal: False


Q1 d)

In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

# Get unique values and their counts
values, counts = np.unique(x, return_counts=True)

# Find the index of the maximum count
max_count_index = np.argmax(counts)

# Most frequent value
most_frequent_value = values[max_count_index]

print("Most frequent value:", most_frequent_value)

# Find indices where this value occurs
indices = np.where(x == most_frequent_value)[0]
print("Indices of most frequent value:", indices)


Most frequent value: 1
Indices of most frequent value: [0 5 7 8 9]


Q1 e)

In [ ]:
import numpy as np

gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')

# Sum of all elements
total_sum=gfg.sum()
print("Sum of all elements:", total_sum)

# Sum of elements row-wise (axis=1)
row_sum = gfg.sum(axis=1)
print("Row-wise sum:\n", row_sum)

# Sum of elements column-wise (axis=0)
col_sum = gfg.sum(axis=0)
print("Column-wise sum:\n", col_sum)



Sum of all elements: 45
Row-wise sum:
 [[14]
 [16]
 [15]]
Column-wise sum:
 [[20  9 16]]


Q1 f)

In [ ]:
import numpy as np 

n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])


# 1. Sum of diagonal elements (trace)
diag_sum = np.trace(n_array)
print("Sum of diagonal elements:", diag_sum)

# 2. Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors (each column corresponds to an eigenvector):\n", eigenvectors)

# 3. Inverse of the matrix
try:
    inv_matrix = np.linalg.inv(n_array)
    print("\nInverse of the matrix:\n", inv_matrix)
except np.linalg.LinAlgError:
    print("\nMatrix is singular and cannot be inverted.")

# 4. Determinant of the matrix
determinant = np.linalg.det(n_array)
print("\nDeterminant of the matrix:", determinant)


Sum of diagonal elements: 176

Eigenvalues:
 [98.16835147 28.097044   49.73460452]

Eigenvectors (each column corresponds to an eigenvector):
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

Inverse of the matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

Determinant of the matrix: 137180.0000000001


Q1 g)

In [ ]:
import numpy as np

p=np.array([[1,2],[2,3]])
q=np.array([[4,5],[6,7]])


# Matrix multiplication
product = np.dot(p, q)  # or p @ q

print("Product of p and q:\n", product)

#To find the covariance matrix, you need a dataset where rows represent variables and columns 
#represent observations (or vice versa). Here, you can stack the arrays p and q as vectors and compute covariance:

# Flatten the matrices to 1D arrays (vectors)
p_flat = p.flatten()
q_flat = q.flatten()

# Stack the vectors as rows
data = np.vstack((p_flat, q_flat))

# Compute covariance matrix
cov_matrix = np.cov(data)

print("\nCovariance matrix:\n", cov_matrix)



Product of p and q:
 [[16 19]
 [26 31]]

Covariance matrix:
 [[0.66666667 1.        ]
 [1.         1.66666667]]


In [ ]:
import numpy as np

p=np.array([[1,2],[2,3],[4,5]])
q=np.array([[4,5,1],[6,7,2]])


# Matrix multiplication
product = np.dot(p, q)  # or p @ q

print("Product of p and q:\n", product)

#To find the covariance matrix, you need a dataset where rows represent variables and columns 
#represent observations (or vice versa). Here, you can stack the arrays p and q as vectors and compute covariance:

# Flatten the matrices to 1D arrays (vectors)
p_flat = p.flatten()
q_flat = q.flatten()

# Stack the vectors as rows
data = np.vstack((p_flat, q_flat))

# Compute covariance matrix
cov_matrix = np.cov(data)

print("\nCovariance matrix:\n", cov_matrix)



Product of p and q:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance matrix:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


Q1 h)

In [ ]:
import numpy as np

x=np.array([2,3,4],[3,2,9])
y=np.array([1,5,0],[5,10,3])

# 1. Inner Product (Dot Product)
inner_product = np.dot(x, y.T)  # y.T is the transpose of y
print("Inner Product (Dot Product):\n", inner_product)

# 2. Outer Product
# For outer product, we treat both vectors as 1D arrays
outer_product = np.outer(x.flatten(), y.flatten())  # Flattening to 1D vectors
print("\nOuter Product:\n", outer_product)

# 3. Cartesian Product
# Cartesian product involves combining each element of x with each element of y.
# np.meshgrid is used for Cartesian product.
cartesian_product = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print("\nCartesian Product:\n", cartesian_product)

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [ ]:
import numpy as np

# Correct way to define 2D arrays
x = np.array([[2, 3, 4], [3, 2, 9]])  # Two rows and three columns
y = np.array([[1, 5, 0], [5, 10, 3]])  # Two rows and three columns

# 1. Inner Product (Dot Product)
inner_product = np.dot(x, y.T)  # y.T is the transpose of y
print("Inner Product (Dot Product):\n", inner_product)

# 2. Outer Product
# For outer product, we treat both vectors as 1D arrays
outer_product = np.outer(x.flatten(), y.flatten())  # Flattening to 1D vectors
print("\nOuter Product:\n", outer_product)

# 3. Cartesian Product
# Cartesian product involves combining each element of x with each element of y.
# np.meshgrid is used for Cartesian product.
cartesian_product = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print("\nCartesian Product:\n", cartesian_product)

Inner Product (Dot Product):
 [[17 52]
 [13 62]]

Outer Product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian Product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2 a)

In [6]:
import numpy as np 

array = np.array([[1, -2, 3],[-4, 5, -6]]) 

# i) element-wise absolute value
abs_array = np.abs(array)
print("absolute value:\n",abs_array)

# ii)
# Flattened array
flattened = array.flatten()
percentiles_flat = np.percentile(flattened, [25, 50, 75])
print('Flattened array:\n',percentiles_flat)

# Percentiles for each column
percentiles_cols = np.percentile(array, [25, 50, 75], axis=0)
print('Percentiles for each column:\n',percentiles_cols)

# Percentiles for each row
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print('Percentiles for each row:\n',percentiles_rows)

# iii)
# Flattened
mean_flat = np.mean(flattened)
print('mean of flattened:\n',mean_flat)

median_flat = np.median(flattened)
print('median of flattened:\n',median_flat)

std_flat = np.std(flattened)
print('standard deviation of flattened:\n',std_flat)

# Per column
mean_col = np.mean(array, axis=0)
print('mean per column:\n',mean_col)

median_col = np.median(array, axis=0)
print('median per column:\n',median_col)

std_col = np.std(array, axis=0)
print('standard deviation per column:\n',std_col)

# Per row
mean_row = np.mean(array, axis=1)
print('mean per row:\n',mean_row)

median_row = np.median(array, axis=1)
print('median per row:\n',median_row)

std_row = np.std(array, axis=1)
print('standard deviation per row:\n',std_row)

absolute value:
 [[1 2 3]
 [4 5 6]]
Flattened array:
 [-3.5 -0.5  2.5]
Percentiles for each column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
mean of flattened:
 -0.5
median of flattened:
 -0.5
standard deviation of flattened:
 3.8622100754188224
mean per column:
 [-1.5  1.5 -1.5]
median per column:
 [-1.5  1.5 -1.5]
standard deviation per column:
 [2.5 3.5 4.5]
mean per row:
 [ 0.66666667 -1.66666667]
median per row:
 [ 1. -4.]
standard deviation per row:
 [2.05480467 4.78423336]


Q2 b)

In [7]:
import numpy as np

a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

floor_values=np.floor(a)
print("Floor values",floor_values)

ceil_values=np.ceil(a)
print("Ceiling values",ceil_values)

truncated_values=np.trunc(a)
print('Truncated values',truncated_values)

rounded_values=np.round(a)
print('Rounded values',rounded_values)

Floor values [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values [-1. -1. -0.  1.  2.  2.  3.]
Truncated values [-1. -1. -0.  0.  1.  1.  3.]
Rounded values [-2. -2. -0.  0.  2.  2.  3.]


Q3 a)

In [16]:
import numpy as np

arr = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array=np.sort(arr)
print('sorted array:\n',sorted_array)

indices_of_sorted=np.argsort(arr)
print('indices of sorted array:\n',indices_of_sorted)

smallest_4 = np.sort(array)[:4]
print('smallest 4:\n',smallest_4)

largest_5 = np.sort(array)[-5:]  # ascending order
print("5 Largest elements:\n", largest_5)

sorted array:
 [ 10  16  16  52  54  62 453]
indices of sorted array:
 [0 3 4 1 5 2 6]
smallest 4:
 [10 16 16 52]
5 Largest elements:
 [ 16  52  54  62 453]


Q3 b)

In [19]:
import numpy as np

arr = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Original array:", array)

# i. Integer elements only (no fractional part)
integers_only = arr[arr % 1 == 0]
print("Integer elements only:", integers_only)

# ii. Float elements only (have fractional part)
floats_only = arr[arr % 1 != 0]
print("Float elements only:", floats_only)

Original array: [ 10  52  62  16  16  54 453]
Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]
